#print(len("sumana reddy"))
#print(len("12345"))
#print(len("ABCDEFGHIJKLMNOPQRSTUVWXYZ"))
#length=len("sumana reddy")
#print("your name has"+str(length)+"charecters")
#new_length=str(length)
#print(type(new_length))
#print(type(length))

#print("10\n"+"10")
#print(int(10)+int(10))
#print(10+float(0.05))
#name=(1234)
#print(39+int(name))
#name_1=433
#name_2=533
#print(40+int(name_1+name_2))
#first_number=input("enter the first number:")
#second_number=input("enter the second number:")
#add=int(first_number)+int(second_number)
#print(add)
first_name=input("enter the first_name:")
second_name=input("enter the swcond_name:")
sum=int(first_name)+int(second_name)
print(sum)